name: PeterGasca
favicon: null
layout_spectrum: 0.7981701935641468
typography_spectrum: 0.8869109724182636
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.580139865167439
  lightness: 0.1301641606260091
  saturation: 0.5292262847069651
  rhythmicContrast: 0.4839639014098793
purpose: []
