name: Peter Gasca
favicon: null
layout_spectrum: 0.97327
typography_spectrum: 0.35339
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f3b4a3'
    - '#000000'
    - '#2393bb'
    - '#9e4e43'
  brandStrength: 0.580139865167439
  lightness: 0.1301641606260091
  saturation: 0.5292262847069651
  rhythmicContrast: 0.5
purpose: []
